name: advent-of-code
version: 0.1.0.0
github: '1gmar/advent-of-code-2019'
license: BSD3
author: 'Igor Marta'

extra-source-files:
  - README.md
  - ChangeLog.md

description: Please see the README on GitHub at <https://github.com/1gmar/advent-of-code-2019#readme>

dependencies:
  - base >= 4.7 && < 5

default-extensions:
  - RecordWildCards
  - LambdaCase
  - TupleSections

library:
  source-dirs: src
  exposed-modules:
    - Day1
    - Day2
    - Day3
    - Day4
    - Day5
    - Day6
    - Day7
    - Day8
    - Day9
    - Day10
    - Day11
    - Day12
    - Day13
    - Day14
    - Day15
    - Day16
    - Day17
  dependencies:
    - vector
    - mtl
    - transformers

executables:
  advent-of-code-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - advent-of-code

tests:
  advent-of-code-test:
    main: MainTest.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - advent-of-code
