name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup stack
      uses: mstksg/setup-stack@v1

    - name: Install dependencies
      run: |
        stack --no-terminal setup

    - name: Build
      run: |
        stack --no-terminal bench

    - name: Run tests
      run: stack --no-terminal test
