name: Haskell CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup stack
        uses: mstksg/setup-stack@v2

      - name: Setup GHC
        run: stack --no-terminal setup

      - name: Build & run tests
        run: stack --no-terminal test
