name: Haskell CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup stack
        uses: actions/setup-haskell@v1.1.4
        with:
          enable-stack: true
          stack-no-global: true
          stack-version: '2.5.1'

      - name: Build
        run: stack --no-terminal build

      - name: Run Tests
        run: stack --no-terminal test
